name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install GCC 13
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-13 g++-13

    - name: Set up GCC 13 as default
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100

    - name: Build and test
      run: ./build.sh -c -d -t --compiler gcc
